// <auto-generated>
//     Generated from Localization\Strings.resx by GenerateStringsAccessor in
//     TCFModManager.App.csproj. Edits are overwritten by the next build.
// </auto-generated>

namespace TCFModManager.App.Localization;

internal static class Strings
{
    internal static System.Resources.ResourceManager ResourceManager { get; } = new(
        "TCFModManager.App.Localization.Strings", typeof(Strings).Assembly);

    internal static string Meta_LanguageName => LocalizationService.Get("Meta_LanguageName");
    internal static string Meta_ShippedLanguages => LocalizationService.Get("Meta_ShippedLanguages");
}
