#!/usr/bin/env python3
"""
Builds the GitHub wiki pages in wiki/ from the two published guides in docs/.

    python tools/build-wiki.py

The guides stay the source of truth - sp-mod-guide.md is still what goes on the app's sp-mod page
and what the README copies - so edit those and rerun this, never the pages it writes. Then copy
wiki/*.md into a clone of https://github.com/TheCrimsonFckr/TCFModManager.wiki.git and push.

What it converts:
  - each sp-mod tab (### under the {.tabset}) becomes its own page, one heading level up
  - each section of the Server Map guide (# If you run the server, ...) becomes its own page
  - "#### warning" / "#### information" blocks become GitHub alerts
  - "see the X tab" becomes a link to that page, and "here on sp-mod" / "this page" wording that
    only made sense on sp-mod points at the sp-mod page instead
  - Home, _Sidebar and _Footer are written from the page list
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = ROOT / "wiki"

MOD_PAGE = "https://sp-mod.com/mod/2945/tcf-mod-manager"
ISSUES = MOD_PAGE + "#issues"
REPO = "https://github.com/TheCrimsonFckr/TCFModManager"

MARKER = "<!-- Generated by tools/build-wiki.py"


def notice(source):
    return f"{MARKER} from docs/{source}. Edit the guide and rebuild - changes made here are overwritten. -->\n\n"


ALERTS = {"warning": "WARNING", "information": "NOTE", "success": "TIP", "error": "CAUTION"}

# Server Map guide sections get short page names. Windows can't hold both "Server-map.md" (the
# app's page) and "Server-Map.md", so nothing here may differ from a tab's name by case alone.
SERVERMAP_NAMES = {
    "If you run the server": "Server Map hosting",
    "If you are joining a server": "Server Map joining",
    "When something is wrong": "Server Map troubleshooting",
}
SERVERMAP_OVERVIEW = "Server Map guide"

# A tab whose title doesn't make a good page name.
TITLES = {
    "New Issues Feature (beta)": "Reporting issues",
    "Files & logs": "Files and logs",
}


def slug(title):
    t = title.replace("&", "and")
    t = re.sub(r"[^\w\s]", " ", t).strip()
    return re.sub(r"\s+", "-", t)


def anchor(heading):
    # GitHub's heading ids: lowercase, punctuation dropped, spaces to hyphens.
    h = re.sub(r"[*`_]", "", heading).strip().lower()
    h = re.sub(r"[^\w\s-]", "", h)
    return re.sub(r"\s", "-", h)


def convert(lines, shift):
    """Headings move up by `shift` levels; warning/information headings become alerts."""
    out = []
    i = 0
    while i < len(lines):
        line = lines[i]
        m = re.match(r"^(#{2,6})\s+(.*?)\s*$", line)
        if m and m.group(2).lower() in ALERTS:
            kind = ALERTS[m.group(2).lower()]
            i += 1
            while i < len(lines) and not lines[i].strip():
                i += 1
            body = []
            while i < len(lines) and lines[i].strip() and not lines[i].startswith("#"):
                body.append(lines[i])
                i += 1
            out.append(f"> [!{kind}]")
            out.extend("> " + b for b in body)
            out.append("")
            continue
        if m:
            level = max(2, len(m.group(1)) - shift)
            text = m.group(2).rstrip(":")
            out.append("#" * level + " " + text)
        else:
            out.append(line.rstrip())
        i += 1
    return tidy(out)


def tidy(lines):
    text = "\n".join(lines).strip("\n")
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text + "\n"


def contents(body):
    heads = re.findall(r"^## (.+)$", body, flags=re.M)
    if len(heads) < 3:
        return ""
    return "\n".join(f"- [{h}](#{anchor(h)})" for h in heads) + "\n\n"


# ------------------------------------------------------------------------------------------------
# sp-mod-guide.md
# ------------------------------------------------------------------------------------------------

def spmod_pages():
    src = (DOCS / "sp-mod-guide.md").read_text(encoding="utf-8").splitlines()

    start = next(i for i, l in enumerate(src) if re.match(r"^##\s*\{\.tabset\}", l))
    intro = [l for l in src[:start] if l.strip() != "#### Guide and Information"]

    tabs, current = [], None
    for line in src[start + 1:]:
        if line.strip() == "{.endtabset}":
            break
        m = re.match(r"^###\s+(.+?)\s*$", line)
        if m:
            current = [m.group(1), []]
            tabs.append(current)
        elif current:
            current[1].append(line)

    names = {t: TITLES.get(t, t) for t, _ in tabs}

    def relink(text):
        text = text.replace(
            "built directly against the sp-mod catalog you're reading this on",
            f"built directly against the [sp-mod]({MOD_PAGE}) catalog")
        text = text.replace("This page is the full reference.", "This wiki is the full reference.")
        text = text.replace("` from this page.", f"` from [its sp-mod page]({MOD_PAGE}).")
        text = text.replace("from its own page here on sp-mod",
                            f"from [its own page on sp-mod]({MOD_PAGE})")
        text = text.replace("The app has its own page here on sp-mod",
                            f"The app has [its own page on sp-mod]({MOD_PAGE})")
        text = text.replace("the mod's page here on sp-mod", "the mod's page on sp-mod")
        text = text.replace("a link to its page here.", "a link to its page on sp-mod.")
        text = text.replace("the file this page's own Download button serves",
                            "the file the app's sp-mod page serves from its own Download button")
        text = text.replace("and points you at this page.",
                            f"and points you at [the app's sp-mod page]({MOD_PAGE}).")
        for tab, name in names.items():
            text = re.sub(r"the \**" + re.escape(tab) + r"\** tab\b", f"[{name}]({slug(name)})", text)
        return text

    pages = []
    for tab, body in tabs:
        name = names[tab]
        text = relink(convert(body, 2))
        pages.append((name, notice("sp-mod-guide.md") + text))

    home_intro = relink(tidy([l.rstrip() for l in intro]))
    return home_intro, pages


# ------------------------------------------------------------------------------------------------
# server-map-guide.md
# ------------------------------------------------------------------------------------------------

def servermap_pages():
    src = (DOCS / "server-map-guide.md").read_text(encoding="utf-8").splitlines()

    sections, current = [], ["", []]
    sections.append(current)
    for line in src:
        m = re.match(r"^#\s+(.+?)\s*$", line)
        if m and m.group(1) != "{.tabset}":
            current = [m.group(1), []]
            sections.append(current)
            continue
        if line.strip() in ("# {.tabset}", "{.endtabset}", "How Do I?...", "Troubleshooting..."):
            continue
        current[1].append(line)

    # The first heading is the guide's own title; what sits under it is the overview.
    sections = [s for s in sections if s[0] or any(l.strip() for l in s[1])]
    intro_title, intro = sections[0]
    rest = sections[1:]

    # The short closing section belongs on the overview page rather than a page of its own.
    tail = [s for s in rest if s[0].lower().startswith("what it does not do")]
    rest = [s for s in rest if s not in tail]

    pages = []
    for title, body in rest:
        name = SERVERMAP_NAMES.get(title, "Server Map " + title)
        text = convert(body, 1)
        lead = f"**{title}**" + (" - how do I..." if title.lower().startswith("if ") else "") + "\n\n"
        pages.append((name, notice("server-map-guide.md") + lead + contents(text) + text))

    overview = convert(intro, 2)
    for title, body in tail:
        overview += "\n## " + title + "\n\n" + convert(body, 1)
    overview += "\n## Pages\n\n" + "\n".join(f"- [{t}]({slug(n)})" for t, n in zip((s[0] for s in rest), (n for n, _ in pages))) + "\n"
    overview += f"\nThe Server Map mod is published as an addon on [the app's sp-mod page]({MOD_PAGE}).\n"

    return (SERVERMAP_OVERVIEW, notice("server-map-guide.md") + overview), pages, intro_title


# ------------------------------------------------------------------------------------------------

def main():
    home_intro, spmod = spmod_pages()
    (sm_name, sm_overview), servermap, _ = servermap_pages()
    sm_titles = {v: k for k, v in SERVERMAP_NAMES.items()}

    # The app's Server map page explains the page; the guide behind it explains the mod.
    spmod = [(n, t + f"\nThe whole Server Map guide - installing the mod, publishing a list, joining and troubleshooting - starts at [{sm_name}]({slug(sm_name)}).\n"
              if n == "Server map" else t) for n, t in spmod]

    pages = list(spmod) + [(sm_name, sm_overview)] + list(servermap)

    home = notice("sp-mod-guide.md") + "# TCF Mod Manager\n\n" + home_intro + "\n## The guide\n\n"
    home += "\n".join(f"- [{n}]({slug(n)})" for n, _ in spmod) + "\n"
    home += "\n## Server Map\n\n"
    home += f"- [{sm_name}]({slug(sm_name)})\n"
    home += "\n".join(f"- [{sm_titles.get(n, n)}]({slug(n)})" for n, _ in servermap) + "\n"
    home += f"\nDownload the app from [its sp-mod page]({MOD_PAGE}). Source is in [the repository]({REPO}).\n"

    sidebar = MARKER + ". -->\n\n**[Home](Home)**\n\n**The guide**\n\n"
    sidebar += "\n".join(f"- [{n}]({slug(n)})" for n, _ in spmod) + "\n\n**Server Map**\n\n"
    sidebar += f"- [Overview]({slug(sm_name)})\n"
    sidebar += "\n".join(f"- [{sm_titles.get(n, n)}]({slug(n)})" for n, _ in servermap) + "\n"

    footer = MARKER + ". -->\n\n" + f"[TCF Mod Manager on sp-mod]({MOD_PAGE}) · [Report a problem]({ISSUES})\n"

    OUT.mkdir(exist_ok=True)

    # Only pages this script wrote are cleared, so a renamed tab doesn't leave its old page behind.
    for old in OUT.glob("*.md"):
        if old.read_text(encoding="utf-8").startswith(MARKER):
            old.unlink()

    files = {"Home": home, "_Sidebar": sidebar, "_Footer": footer}
    files.update({slug(n): t for n, t in pages})
    for name, text in files.items():
        (OUT / f"{name}.md").write_text(text, encoding="utf-8", newline="\n")

    print(f"{len(files)} pages written to {OUT}")


if __name__ == "__main__":
    main()
